c99:
	gcc -Wall -Werror -Wshadow -std=c99 main.c

c89:
	gcc -Wall -Werror -Wshadow -std=c89 main.c

ansi:
	gcc -Wall -Werror -Wshadow -std=c89 -ansi main.c

pedantic99:
	gcc -Wall -Werror -Wshadow -std=c99 -Wpedantic main.c

pedantic89:
	gcc -Wall -Werror -Wshadow -std=c89 -Wpedantic main.c

tcc:
	tcc -Wall -Werror main.c
